default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: simple-todos-backend_development

test:
  <<: *default
  database: simple-todos-backend_test


production:
  <<: *default
  database: simple-todos-backend_production
  username: simple-todos-backend
  password: <%= ENV['SIMPLE-TODOS-BACKEND_DATABASE_PASSWORD'] %>
